<?php

/* 
 * An exception can be thrown, and catched within PHP.
 * The code can be inside a try block to facilitate the capture of potential exceptions.
 * Each try block must have at least one catch or finally corresponding block.
 */

function inverse($x) {
    if (!$x) {
        throw new Exception('Divisi贸n por cero.');
    }
    return 1/$x;
}

try {
    echo inverse(5) . "\n";
} catch (Exception $e) {
    echo 'Excepci贸n capturada: ',  $e->getMessage(), "\n";
} finally {
    echo "Primer finally.\n";
}

try {
    echo inverse(0) . "\n";
} catch (Exception $e) {
    echo 'Excepci贸n capturada: ',  $e->getMessage(), "\n";
} finally {
    echo "Segundo finally.\n";
}

// Continuar ejecuci贸n
echo 'Hola Mundo\n';

?>